worker_heartbeat_timeout: 300000
num_workers: 4

logging:
    level: info

metrics:
  type: statsd
  host: localhost
  port: 9125

services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        localsettings: ./lib/config/localSettings.js

        # Use selective serialization (default false)
        useSelser: true

        # IW-2729: Use batch API interface for communicating with MediaWiki
        useBatchAPI: true

        limits:
          wt2html:
            # IW-3041: Match Parsoid's max wikitext size to MediaWiki's $wgMaxArticleSize value - 2 MiB
            maxWikitextSize: 2000000
