worker_heartbeat_timeout: 300000

logging:
    level: info

metrics:
  type: statsd
  host: localhost
  port: 9125

services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        localsettings: ./lib/config/localSettings.js

        # Use selective serialization (default false)
        useSelser: true
        
        # IW-2729: Use batch API interface for communicating with MediaWiki
        useBatchAPI: true
