worker_heartbeat_timeout: 300000
num_workers: 0

logging:
    level: info

metrics:
  - type: prometheus
    port: 8081

services:
  - module: lib/index.js
    entrypoint: apiServiceWorker
    conf:
        localsettings: ./lib/config/localSettings.js

        # Use selective serialization (default false)
        useSelser: true

        # IW-2729: Use batch API interface for communicating with MediaWiki
        useBatchAPI: true

        # Enable using compute workers to parse requests.
        useWorker: true
        # The number of workers in the pool spawned by each http worker
        # to call out for parsing
        # ceil(cpu request / `num_workers`) + 1
        cpu_workers: 3

        maxConcurrentCalls: 8

        limits:
          wt2html:
            # IW-3041: Match Parsoid's max wikitext size to MediaWiki's $wgMaxArticleSize value - 2 MiB
            maxWikitextSize: 2000000
