---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: parsoid-redux
  name: parsoid-redux
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: parsoid-redux
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsoid-redux
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: parsoid-redux
    spec:
      containers:
      - name: parsoid-redux
        image: artifactory.wikia-inc.com/services/parsoid-redux:0.1.6
        env:
        - name: ENV
          value: dev
        - name: PARSOID_PORT
          value: "8080"
        resources:
          limits:
            memory: 1.4Gi
          requests:
            cpu: 500m
            memory: 700Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: parsoid-redux
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: dev.poz-dev.k8s.wikia.net
    http:
      paths:
      - path: /parsoid-redux
        backend:
          serviceName: parsoid-redux
          servicePort: 80
