---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unified-platform-parsoid
  name: unified-platform-parsoid
  namespace: ${env}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: unified-platform-parsoid
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-platform-parsoid
  namespace: ${env}
spec:
  selector:
    matchLabels:
      app: unified-platform-parsoid
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: unified-platform-parsoid
    spec:
      containers:
      - name: unified-platform-parsoid
        image: ${imageName}
        env:
        - name: ENV
          value: ${env}
        - name: PARSOID_PORT
          value: "8080"
        resources:
          limits:
            memory: 1.4Gi
          requests:
            cpu: 500m
            memory: 700Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: unified-platform-parsoid
  namespace: ${env}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: ${env}.${datacenter}.k8s.wikia.net
    http:
      paths:
      - path: /unified-platform-parsoid
        backend:
          serviceName: unified-platform-parsoid
          servicePort: 80
