name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter and tests
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm test
        env:
          CI: true
